---
- name: Deploy Scientific Calculator from Docker Hub
  hosts: localhost
  connection: local
  become: false

  vars:
    image_name: "mayank2101/spe-miniproject-calculator"
    image_tag: "{{ image_tag }}"

  tasks:

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: spe-miniproject-calculator-container
        state: absent

    - name: Run new container
      docker_container:
        name: spe-miniproject-calculator-container
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        tty: true
        interactive: true
        detach: true
